services:

    app.shop_user_provider.email_or_name_based:
        class: App\Component\User\Provider\UsernameOrEmailProvider
        arguments:
            $supportedUserClass: '' #ShopUser Entity
            $userRepository: '' #ShopUser Repository

    app.controller.shop_user:
        class: App\Component\User\Controller\UserController
        arguments:
            $userRepository: ''
            $tokenTTL: ''