services:
    App\Component\User\Provider\UsernameOrEmailProvider:
        parent: App\Component\User\Provider\AbstractUserProvider
        arguments:
            index_0: '' #ShopUser Entity
            index_1: '' #ShopUser Repository
        #alias: app.shop_user_provider.email_or_name_based

    App\Component\User\Controller\UserController:
        $userRepository: ''
        #alias: app.controller.shop_user

    App\Component\User\Controller\UserController:
        $userRepository: '' #ShopUser Repository
        #alias: app.controller.shop_user