services:

    app.security.shop_user_impersonator:
        class: App\Component\User\Security\UserImpersonator
        arguments:
            $firewallContextName: 'shop'

    app.admin_user_provider.email_or_name_based:
        class: App\Component\User\Provider\UsernameOrEmailProvider
        arguments:
            $supportedUserClass: '' #AdminUser Entity
            $userRepository: '' #AdminUser Repository

    app.controller.admin_user:
        class: App\Component\User\Controller\UserController
        arguments:
            $userRepository: ''
            $tokenTTL: ''