<?php

namespace App\Ecommerce\Shop\Repository;

use App\Component\Resource\Repository\EntityRepository;
use App\Component\User\Repository\UserRepositoryInterface;

/**
 * ShopUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopUserRepository extends EntityRepository implements UserRepositoryInterface
{
    /**
     * {@inheritdoc}
     */
    public function findOneByEmail($email)
    {
        return $this->createQueryBuilder('o')
            ->innerJoin('o.customer', 'customer')
            ->addSelect('customer')
            ->andWhere('customer.emailCanonical = :email')
            ->setParameter('email', $email)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * {@inheritdoc}
     */
    public function findOneByConfirmationToken($token)
    {
        return $this->createQueryBuilder('o')
            ->innerJoin('o.customer', 'customer')
            ->addSelect('customer')
            ->andWhere('o.confirmationToken = :token')->setParameter('token', $token)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
